=== romeod75/instructionset/instructionSet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<!-- ************************************************************************* -->
	<!-- definition of simple elements -->
	<!-- ************************************************************************* -->
	<xsd:element name="instructionSetName" type="xsd:string"/>
	<xsd:element name="version" type="xsd:string"/>
	<xsd:element name="author" type="xsd:string"/>
	<xsd:element name="instructionSetDescription" type="xsd:string"/>
	<xsd:element name="commandDescription" type="xsd:string"/>
	<!-- ************************************************************************* -->
	<!-- root element instructionSet -->
	<!-- ************************************************************************* -->
	<xsd:element name="instructionSet">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="instructionSetName"/>
				<xsd:element ref="version"/>
				<xsd:element ref="author"/>
				<xsd:element ref="instructionSetDescription"/>
				<xsd:element name="commands" type="Commands"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- ************************************************************************* -->
	<!-- Commands -->
	<!-- ************************************************************************* -->
	<xsd:complexType name="Commands">
		<xsd:sequence>
			<xsd:element name="command" minOccurs="1" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="commandDescription" type="xsd:string" minOccurs="0"/>
						<!-- [Optional] How many times to repeat this specific command? Default is 1 cant be 0-->
						<xsd:element name="repeat" minOccurs="0">
							<xsd:simpleType>
								<xsd:restriction base="xsd:positiveInteger">
									<xsd:minInclusive value="2"/>
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:element>
						<xsd:element name="actions" type="Actions"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!-- ************************************************************************* -->
	<!-- Actions -->
	<!-- ************************************************************************* -->
	<xsd:complexType name="Actions">
		<xsd:annotation>
			<xsd:documentation>At least one of move or turn required. Could be both</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="action" minOccurs="1" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="move" type="moveType" minOccurs="0"/>
						<xsd:element name="turn" type="turnType" minOccurs="0"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!-- ************************************************************************* -->
	<!-- Move -->
	<!-- ************************************************************************* -->
	<xsd:complexType name="moveType">
		<xsd:sequence>
			<!-- [Mandatory] where? -->
			<xsd:element name="direction">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="forward"/>
						<xsd:enumeration value="back"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!-- [Mandatory] how far? -->
			<xsd:element name="distance">
				<xsd:simpleType>
					<xsd:restriction base="xsd:decimal">
						<xsd:minInclusive value="1"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!-- [Optional] Do not output to screen -->
			<xsd:element name="invisible" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="Y"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!-- [Optional] Use color other than black -->
			<xsd:element name="color" minOccurs="0">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="blue"/>
						<xsd:enumeration value="green"/>
						<xsd:enumeration value="orange"/>
						<xsd:enumeration value="red"/>
						<xsd:enumeration value="yellow"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!-- ************************************************************************* -->
	<!-- Turn -->
	<!-- ************************************************************************* -->
	<xsd:complexType name="turnType">
		<xsd:sequence>
			<!-- [Manadtory] Which direction -->
			<xsd:element name="direction">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="left"/>
						<xsd:enumeration value="right"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<!-- [Manadtory] What angel -->
			<xsd:element name="angle">
				<xsd:simpleType>
					<xsd:restriction base="xsd:positiveInteger">
						<xsd:minInclusive value="1"/>
						<xsd:maxInclusive value="360"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== romeod75/instructionset/examples/multichoice.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2012 rel. 2 sp1 (http://www.altova.com)-->
<instructionSet xsi:noNamespaceSchemaLocation="instructionSet.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<instructionSetName>MultiChoice Instruction Set Demo</instructionSetName>
	<version>1.0</version>
	<author>Romeo Dickason</author>
	<instructionSetDescription>Will draw an image as per the project specification. See image 1.1.</instructionSetDescription>
	<commands>
		<command>
			<commandDescription>Draw line 1</commandDescription>
			<actions>
				<action>
					<turn>
						<direction>right</direction>
						<angle>90</angle>
					</turn>
				</action>
				<action>
					<move>
						<direction>forward</direction>
						<distance>500</distance>
					</move>
				</action>
			</actions>
		</command>
		<command>
			<commandDescription>Draw line 2</commandDescription>
			<actions>
				<action>
					<turn>
						<direction>left</direction>
						<angle>150</angle>
					</turn>
				</action>
				<action>
					<move>
						<direction>forward</direction>
						<distance>577.35</distance>
					</move>
				</action>
			</actions>
		</command>
		<command>
			<commandDescription>Draw line 3</commandDescription>
			<actions>
				<action>
					<turn>
						<direction>right</direction>
						<angle>150</angle>
					</turn>
				</action>
				<action>
					<move>
						<direction>forward</direction>
						<distance>500</distance>
					</move>
				</action>
			</actions>
		</command>
		<command>
			<commandDescription>Draw line 4</commandDescription>
			<actions>
				<action>
					<turn>
						<direction>left</direction>
						<angle>135</angle>
					</turn>
				</action>
				<action>
					<move>
						<direction>forward</direction>
						<distance>353.55</distance>
					</move>
				</action>
			</actions>
		</command>
		<command>
			<commandDescription>Draw line 5</commandDescription>
			<actions>
				<action>
					<turn>
						<direction>left</direction>
						<angle>90</angle>
					</turn>
				</action>
				<action>
					<move>
						<direction>forward</direction>
						<distance>353.55</distance>
					</move>
				</action>
			</actions>
		</command>
		<command>
			<commandDescription>Draw line 6</commandDescription>
			<actions>
				<action>
					<turn>
						<direction>left</direction>
						<angle>45</angle>
					</turn>
				</action>
				<action>
					<move>
						<direction>forward</direction>
						<distance>288.68</distance>
					</move>
				</action>
			</actions>
		</command>	
		<command>
			<commandDescription>Draw line 7</commandDescription>
			<actions>
				<action>
					<turn>
						<direction>left</direction>
						<angle>120</angle>
					</turn>
				</action>
				<action>
					<move>
						<direction>forward</direction>
						<distance>577.35</distance>
					</move>
				</action>
			</actions>
		</command>		
		<command>
			<commandDescription>Draw line 8</commandDescription>
			<actions>
				<action>
					<turn>
						<direction>right</direction>
						<angle>120</angle>
					</turn>
				</action>
				<action>
					<move>
						<direction>forward</direction>
						<distance>288.68</distance>
					</move>
				</action>
			</actions>
		</command>				
	</commands>
</instructionSet>

=== romeod75/instructionset/examples/square.xml
<?xml version="1.0" encoding="UTF-8"?>
<instructionSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:///C:/LOGOInstructor/instructionSet.xsd">
	<instructionSetName>Instruction set for square with different coloured sides</instructionSetName>
	<version>1.0</version>
	<author>Romeo Dickason</author>
	<instructionSetDescription>Will draw a square with the sides four different colours and one side dashed.</instructionSetDescription>
	<commands>
		<command>
			<commandDescription>Will draw the first side in red</commandDescription>
			<actions>
				<action>
					<move>
						<direction>forward</direction>
						<distance>250</distance>
						<color>red</color>
					</move>
				</action>
			</actions>
		</command>
		<command>
			<commandDescription>Turn the pointer right</commandDescription>
			<actions>
				<action>
					<turn>
						<direction>right</direction>
						<angle>90</angle>
					</turn>
				</action>
			</actions>
		</command>
		<command>
			<commandDescription>Will draw the second side in blue - dotted</commandDescription>
			<repeat>50</repeat>
			<actions>
				<action>
					<move>
						<direction>forward</direction>
						<distance>5</distance>
						<color>blue</color>
					</move>
				</action>
				<action>
					<move>
						<direction>forward</direction>
						<distance>5</distance>
						<invisible>Y</invisible>
					</move>
				</action>				
			</actions>
		</command>
		<command>
			<commandDescription>Will draw the third side in green</commandDescription>
			<actions>
				<action>
					<turn>
						<direction>right</direction>
						<angle>90</angle>
					</turn>
				</action>
				<action>
					<move>
						<direction>forward</direction>
						<distance>250</distance>
						<color>green</color>
					</move>
				</action>
			</actions>
		</command>
		<command>
			<commandDescription>Will draw the fourth side in orange</commandDescription>
			<actions>
				<action>
					<turn>
						<direction>right</direction>
						<angle>90</angle>
					</turn>
				</action>
				<action>
					<move>
						<direction>forward</direction>
						<distance>500</distance>
						<color>orange</color>
					</move>
				</action>
			</actions>
		</command>
	</commands>
</instructionSet>

=== romeod75/instructionset/examples/octagon.xml
<?xml version="1.0" encoding="UTF-8"?>
<instructionSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/LOGOInstructor/instructionSet.xsd">
	<instructionSetName>Instruction set to draw a octagon.</instructionSetName>
	<version>1.0</version>
	<author>Romeo Dickason</author>
	<instructionSetDescription>Draws an octagon with one command repeated 8 times.</instructionSetDescription>
	<commands>
		<command>
			<commandDescription>Move forward so image does not fall off bottom of screen</commandDescription>
			<actions>
				<action>
					<move>						
						<direction>forward</direction>
						<distance>200</distance>
						<invisible>Y</invisible>
					</move>
				</action>
			</actions>
		</command>
		<command>
		<commandDescription>Will draw 8 lines with an angle of 45 to form an octagon</commandDescription>
		<repeat>8</repeat>
			<actions>
				<action>
					<move>
						<direction>forward</direction>
						<distance>100</distance>
					</move>
				</action>
				<action>
					<turn>
						<direction>right</direction>
						<angle>45</angle>
					</turn>
				</action>
			</actions>
		</command>
	</commands>
</instructionSet>

=== romeod75/instructionset/examples/circle.xml
<?xml version="1.0" encoding="UTF-8"?>
<instructionSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:///C:/LOGOInstructor/instructionSet.xsd">
	<instructionSetName>Draws a fance circle with one quarter invisible and the other all a different colour.</instructionSetName>
	<version>1.0</version>
	<author>Romeo Dickason</author>
	<instructionSetDescription>Draw a circle. First quarter: green. Second quarter: invisible (pen up). Third quarter: blue. Fourth quarter: orange.</instructionSetDescription>
	<commands>
		<command>
			<commandDescription>Move forward so image does not fall off bottom of screen</commandDescription>
			<actions>
				<action>
					<move>
						<direction>forward</direction>
						<distance>200</distance>
						<invisible>Y</invisible>
					</move>
					<turn>
						<direction>right</direction>
						<angle>45</angle>
					</turn>
				</action>
			</actions>
		</command>
		<command>
			<commandDescription>Will draw the first quarter in green</commandDescription>
			<repeat>90</repeat>
			<actions>
				<action>
					<move>
						<direction>forward</direction>
						<distance>2</distance>
						<color>green</color>
					</move>
				</action>
				<action>
					<turn>
						<direction>right</direction>
						<angle>1</angle>
					</turn>
				</action>
			</actions>
		</command>
		<command>
			<commandDescription>Will draw the second quarter - invisible (pen up)</commandDescription>
			<repeat>90</repeat>
			<actions>
				<action>
					<move>
						<direction>forward</direction>
						<distance>2</distance>
						<invisible>Y</invisible>
					</move>
				</action>
				<action>
					<turn>
						<direction>right</direction>
						<angle>1</angle>
					</turn>
				</action>
			</actions>
		</command>
		<command>
			<commandDescription>Will draw the second third quarter in blue</commandDescription>
			<repeat>90</repeat>
			<actions>
				<action>
					<move>
						<direction>forward</direction>
						<distance>2</distance>
						<color>blue</color>
					</move>
				</action>
				<action>
					<turn>
						<direction>right</direction>
						<angle>1</angle>
					</turn>
				</action>				
			</actions>			
		</command>
		<command>
			<commandDescription>Will draw the second third quarter in orange</commandDescription>
			<repeat>90</repeat>
			<actions>
				<action>
					<move>
						<direction>forward</direction>
						<distance>2</distance>
						<color>orange</color>
					</move>
				</action>
				<action>
					<turn>
						<direction>right</direction>
						<angle>1</angle>
					</turn>
				</action>
			</actions>
		</command>
	</commands>
</instructionSet>
